<?php /** @var \Magento\Framework\View\Element\Template $block */?>
<?php $viewModel = $block->getData('view_model') ?>

<?php $brandInfo = $viewModel->getBrandInfo() ?>

<h2><?= $brandInfo['name'] ?></h2>

<?php if(isset($brandInfo['description'])): ?>
    <h3>hello world</h3>
<?php endif; ?>

<?php foreach ($brandInfo['collaborations'] as $collaboration): ?>
    <p><?= $collaboration ?></p>
<?php endforeach; ?>
